render:
	dot -Tpng -Gdpi=300 tasks/task-graph.dot -o tasks/task-graph.png
	dot -Tpng -Gdpi=300 tasks/task-control-flow-with-edge-labels.dot -o tasks/task-control-flow-with-edge-labels.png
	dot -Tpng -Gdpi=300 tasks/task-control-flow-without-edge-labels.dot -o tasks/task-control-flow-without-edge-labels.png
