---
name: Compile
on: 
    push:
        tags:
            - '*'
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: 1.21
        - run: make build
        - uses: softprops/action-gh-release@v1
          with:
            files: bin/*
            token: ${{ secrets.GITHUB_TOKEN }}
        
    